// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_AdaptR
int rcpp_AdaptR(std::string PfileName);
RcppExport SEXP AdaptR_rcpp_AdaptR(SEXP PfileNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type PfileName(PfileNameSEXP);
    __result = Rcpp::wrap(rcpp_AdaptR(PfileName));
    return __result;
END_RCPP
}
// rcpp_MuruCompactor
int rcpp_MuruCompactor(std::string PfileName);
RcppExport SEXP AdaptR_rcpp_MuruCompactor(SEXP PfileNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type PfileName(PfileNameSEXP);
    __result = Rcpp::wrap(rcpp_MuruCompactor(PfileName));
    return __result;
END_RCPP
}
