# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_AdaptR <- function(PfileName) {
    .Call('AdaptR_rcpp_AdaptR', PACKAGE = 'AdaptR', PfileName)
}

rcpp_MuruCompactor <- function(PfileName) {
    .Call('AdaptR_rcpp_MuruCompactor', PACKAGE = 'AdaptR', PfileName)
}

